# TLS Secret (Let's Encrypt Certificate)
# To populate this secret with your Let's Encrypt certs:
#   kubectl create secret tls tls-secret \
#     --cert=/path/to/fullchain.pem \
#     --key=/path/to/privkey.pem \
#     --dry-run=client -o yaml | kubectl apply -f -
#
# Or manually base64 encode your certs and replace the values below:
#   cat fullchain.pem | base64 -w 0
#   cat privkey.pem | base64 -w 0
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  # Replace with base64 encoded fullchain.pem from Let's Encrypt
  tls.crt: <BASE64_ENCODED_FULLCHAIN_PEM>
  # Replace with base64 encoded privkey.pem from Let's Encrypt
  tls.key: <BASE64_ENCODED_PRIVKEY_PEM>

---
# Database Persistence
# If needed, create a PersistentVolumeClaim for the database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: campus-one-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Nginx ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
          proxy_pass http://127.0.0.1:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-one-store
  labels:
    app: campus-one-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campus-one-store
  template:
    metadata:
      labels:
        app: campus-one-store
    spec:
      containers:
      # Next.js App Container
      - name: campus-one-store
        image: campus-one-store:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_PATH
          value: "/db/campus.db"
        volumeMounts:
        - name: db-volume
          mountPath: /db
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      # Nginx SSL Proxy Sidecar
      - name: nginx-ssl-proxy
        image: nginx:alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tls-volume
          mountPath: /etc/nginx/ssl
          readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: campus-one-db-pvc
      - name: nginx-conf-volume
        configMap:
          name: nginx-conf
      - name: tls-volume
        secret:
          secretName: tls-secret

---
# Service (HTTPS)
apiVersion: v1
kind: Service
metadata:
  name: campus-one-store-service
spec:
  selector:
    app: campus-one-store
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
